<?xml version="1.0" encoding="UTF-8"?><testrun name="Rerun testAdd()" project="ABCBankingAdmin" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.example.controller.CustomerControllerTest" time="0.194" displayname="CustomerControllerTest" uniqueid="[engine:junit-jupiter]/[class:com.example.controller.CustomerControllerTest]">
    <testcase name="testAdd" classname="com.example.controller.CustomerControllerTest" time="0.194" displayname="testAdd()" uniqueid="[engine:junit-jupiter]/[class:com.example.controller.CustomerControllerTest]/[method:testAdd()]">
      <failure>Wanted but not invoked:
com.example.repo.CustomerRepo#0 bean.save(
    Customer(id=1, Name=Customer A, Username=Customer Username A, Password=null, Age=20, Address=Bangalore, Email=CustomerA@gmail.com, Phone=9000000000, Balance=20000.0)
);
-&gt; at com.example.controller.CustomerControllerTest.testAdd(CustomerControllerTest.java:120)
Actually, there were zero interactions with this mock.
&#13;
	at com.example.controller.CustomerControllerTest.testAdd(CustomerControllerTest.java:120)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
